title: 'Oxygen'
# html lang only
default_lang: 'en'
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'A crazy fast, accessible and GDPR-compliant theme out of the box + build tools.'
# do not remove taxonomy tag (identifier required in templates/partials/footer.html.twig)
taxonomies: [tag]
