title: Default
extends@:
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
          content:
            fields:
              # @start: DEFAULTS
              header.content.items:
                  type: hidden
                  default: '@self.modules'
              # @end: DEFAULTS
              spacer:
                type: spacer
                # title: A title
                # text: Some text
                underline: true
                # ordering@: content
                ordering@: PageMedia
              header.banner:
                ordering@: spacer
                type: fieldset
                title: Banner
                # help: 'optional'
                info: ' click to expand / collapse'
                # text: 'Leave text fields blank'
                icon: camera
                collapsed: false
                collapsible: true
                fields:
                  # see https://github.com/getgrav/grav/issues/3909
                  # Upload field
                  # .mediaCollection:
                  #   disabled: true
                  #   type: file
                  #   # type: pagemedia
                  #   label: Upload image
                  #   sublabel: >
                  #       <i>Recommended size: 1500x960px.</i>
                  #   style: vertical
                  #   destination: 'image://banner'
                  #   multiple: true
                  #   limit: 255
                  #   random_name: false
                  #   avoid_overwriting: false
                  #   accept:
                  #     - image/*
                  .url:
                    # type: pagemediaselect
                    type: mediapicker
                    # folder: 'image://banner'
                    label: Image
                    help: 'Leave blank for none.'
                    sublabel: >
                      <small>Recommended size: 1500x960px. Leave blank for none.</small>
                    preview_images: true
                    accept:
                      - image/*
                  .position:
                    type: text
                    label: Position
                    help: 'CSS values for background-position'
                    default: 'center center'
                  # .headline:
                  #   type: text
                  #   label: (Optional) Headline
                  #   help: 'Leave blank for none.'
                  # .follower.text:
                  #   type: text
                  #   label: (Optional) Follower text
                  #   help: 'Leave blank for none.'
                  # .follower.class:
                  #   type: selectize
                  #   label: (Optional) Follower class
                  #   help: 'Custom pre-defined CSS classes.'
                  #   sublabel: <small>Choose one, multiple or leave blank (default).</small>
                  #   selectize:
                  #       options:
                  #         - text: 'opacity-dark'
                  #           value: 'opacity-dark'
                  #         - text: 'opacity-light'
                  #           value: 'opacity-light'
                  #         - text: 'skew'
                  #           value: 'skew'
                  #         - text: 'small'
                  #           value: 'small'
                  #         - text: 'bold'
                  #           value: 'bold'
                  #         - text: 'italic'
                  #           value: 'italic'
                  #         - text: 'uppercase'
                  #           value: 'uppercase'
                  #         - text: 'normal-case'
                  #           value: 'normal-case'
                  # .blurb.text:
                  #   type: text
                  #   label: (Optional) Blurb text
                  #   help: 'Leave blank for none.'
                  # .blurb.class:
                  #   type: selectize
                  #   label: (Optional) Blurb class
                  #   help: 'Custom pre-defined CSS classes.'
                  #   sublabel: >
                  #       <small>Choose one, multiple or leave blank (default).</small>
                  #   selectize:
                  #       options:
                  #         - text: 'opacity-dark'
                  #           value: 'opacity-dark'
                  #         - text: 'opacity-light'
                  #           value: 'opacity-light'
                  #         - text: 'skew'
                  #           value: 'skew'
                  #         - text: 'small'
                  #           value: 'small'
                  #         - text: 'bold'
                  #           value: 'bold'
                  #         - text: 'italic'
                  #           value: 'italic'
                  #         - text: 'uppercase'
                  #           value: 'uppercase'
                  #         - text: 'normal-case'
                  #           value: 'normal-case'
              header.pageOptions:
                ordering@: banner
                type: fieldset
                title: Page Options
                info: ' click to expand / collapse'
                # underline: true
                icon: cog
                collapsed: false
                collapsible: true
                fields:
                  .noIndex:
                    type: toggle
                    label: Allow this specific page to be indexed by search engines
                    help: '(Default: enabled) This page may be indexed by search engines. Please make sure that the the entire site can be indexed via THEME OPTIONS.'
                    default: 0
                    highlight: 0
                    options:
                      1: PLUGIN_ADMIN.DISABLED
                      0: PLUGIN_ADMIN.ENABLED
                    validate:
                      type: bool
              sectionModules:
                  type: section
                  title: Modules Available
                  text: Additional content can be populated by modules.
                  underline: true
                  ordering@: 99